_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
base_data_dir:
    value: /home/mundus/hrashid173/ChatSim/chatsim/background/mcnerf/
method:
    value: exp/segment-11379226583756500423_6230_810_6250_810_with_camera_labels/exp_coeff_0.15/test_images
scene:
    value: data/waymo_multi_view/segment-11379226583756500423_6230_810_6250_810_with_camera_labels
