name: gs_env
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia/label/cuda-11.8.0 # comment this line if you have cuda 11.8
dependencies:
  - cuda        # comment this line if you have cuda 11.8
  - cuda-nvcc   # comment this line if you have cuda 11.8
  - cudatoolkit=11.8
  - plyfile
  - omegaconf
  - python=3.9
  - pip
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - icecream
  - tqdm
  - imageio